//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personelim.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Personelim.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        internal static string UserRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("UserRegisteredSuccessfully", resourceCulture);
            }
        }
        
        internal static string ErrorDuringRegistration {
            get {
                return ResourceManager.GetString("ErrorDuringRegistration", resourceCulture);
            }
        }
        
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        internal static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        internal static string ErrorDuringLogin {
            get {
                return ResourceManager.GetString("ErrorDuringLogin", resourceCulture);
            }
        }
        
        internal static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        internal static string PasswordResetEmailIfExist {
            get {
                return ResourceManager.GetString("PasswordResetEmailIfExist", resourceCulture);
            }
        }
        
        internal static string EmailCouldNotBeSent {
            get {
                return ResourceManager.GetString("EmailCouldNotBeSent", resourceCulture);
            }
        }
        
        internal static string PasswordResetCodeSent {
            get {
                return ResourceManager.GetString("PasswordResetCodeSent", resourceCulture);
            }
        }
        
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        internal static string CodeVerified {
            get {
                return ResourceManager.GetString("CodeVerified", resourceCulture);
            }
        }
        
        internal static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        internal static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        internal static string BusinessesListed {
            get {
                return ResourceManager.GetString("BusinessesListed", resourceCulture);
            }
        }
        
        internal static string BusinessNotFound {
            get {
                return ResourceManager.GetString("BusinessNotFound", resourceCulture);
            }
        }
        
        internal static string UnauthorizedAction {
            get {
                return ResourceManager.GetString("UnauthorizedAction", resourceCulture);
            }
        }
        
        internal static string BusinessUpdated {
            get {
                return ResourceManager.GetString("BusinessUpdated", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string BusinessCreatedVerificationSent {
            get {
                return ResourceManager.GetString("BusinessCreatedVerificationSent", resourceCulture);
            }
        }
        
        internal static string BusinessVerificationError {
            get {
                return ResourceManager.GetString("BusinessVerificationError", resourceCulture);
            }
        }
        
        internal static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        internal static string InvalidCodeOrBusiness {
            get {
                return ResourceManager.GetString("InvalidCodeOrBusiness", resourceCulture);
            }
        }
        
        internal static string BusinessVerified {
            get {
                return ResourceManager.GetString("BusinessVerified", resourceCulture);
            }
        }
        
        internal static string VerificationError {
            get {
                return ResourceManager.GetString("VerificationError", resourceCulture);
            }
        }
        
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        internal static string DocumentUploaded {
            get {
                return ResourceManager.GetString("DocumentUploaded", resourceCulture);
            }
        }
        
        internal static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        internal static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        internal static string ErrorListingBusinesses {
            get {
                return ResourceManager.GetString("ErrorListingBusinesses", resourceCulture);
            }
        }
        
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        internal static string ImageUploadError {
            get {
                return ResourceManager.GetString("ImageUploadError", resourceCulture);
            }
        }
        
        internal static string NoPermissionViewPersonnel {
            get {
                return ResourceManager.GetString("NoPermissionViewPersonnel", resourceCulture);
            }
        }
        
        internal static string ErrorPersonnelList {
            get {
                return ResourceManager.GetString("ErrorPersonnelList", resourceCulture);
            }
        }
        
        internal static string PersonnelNotFound {
            get {
                return ResourceManager.GetString("PersonnelNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorPersonnelDetail {
            get {
                return ResourceManager.GetString("ErrorPersonnelDetail", resourceCulture);
            }
        }
        
        internal static string ErrorUpdatePersonnel {
            get {
                return ResourceManager.GetString("ErrorUpdatePersonnel", resourceCulture);
            }
        }
        
        internal static string PersonnelUpdated {
            get {
                return ResourceManager.GetString("PersonnelUpdated", resourceCulture);
            }
        }
        
        internal static string TCInvalid {
            get {
                return ResourceManager.GetString("TCInvalid", resourceCulture);
            }
        }
        
        internal static string CannotRemoveSelf {
            get {
                return ResourceManager.GetString("CannotRemoveSelf", resourceCulture);
            }
        }
        
        internal static string NoPermissionRemovePersonnel {
            get {
                return ResourceManager.GetString("NoPermissionRemovePersonnel", resourceCulture);
            }
        }
        
        internal static string PersonnelRemoved {
            get {
                return ResourceManager.GetString("PersonnelRemoved", resourceCulture);
            }
        }
        
        internal static string ErrorRemovePersonnel {
            get {
                return ResourceManager.GetString("ErrorRemovePersonnel", resourceCulture);
            }
        }
        
        internal static string OnlyPdfAllowed {
            get {
                return ResourceManager.GetString("OnlyPdfAllowed", resourceCulture);
            }
        }
        
        internal static string DocumentUploadSuccess {
            get {
                return ResourceManager.GetString("DocumentUploadSuccess", resourceCulture);
            }
        }
        
        internal static string ErrorDocumentUpload {
            get {
                return ResourceManager.GetString("ErrorDocumentUpload", resourceCulture);
            }
        }
        
        internal static string NoPermissionUpdateDocument {
            get {
                return ResourceManager.GetString("NoPermissionUpdateDocument", resourceCulture);
            }
        }
        
        internal static string DocumentUpdateSuccess {
            get {
                return ResourceManager.GetString("DocumentUpdateSuccess", resourceCulture);
            }
        }
        
        internal static string ErrorDocumentUpdate {
            get {
                return ResourceManager.GetString("ErrorDocumentUpdate", resourceCulture);
            }
        }
        
        internal static string NoPermissionViewDocument {
            get {
                return ResourceManager.GetString("NoPermissionViewDocument", resourceCulture);
            }
        }
        
        internal static string FileNotFoundOnServer {
            get {
                return ResourceManager.GetString("FileNotFoundOnServer", resourceCulture);
            }
        }
        
        internal static string NoPermissionDeleteDocument {
            get {
                return ResourceManager.GetString("NoPermissionDeleteDocument", resourceCulture);
            }
        }
        
        internal static string DocumentDeleteSuccess {
            get {
                return ResourceManager.GetString("DocumentDeleteSuccess", resourceCulture);
            }
        }
        
        internal static string ErrorDocumentDelete {
            get {
                return ResourceManager.GetString("ErrorDocumentDelete", resourceCulture);
            }
        }
        
        internal static string NoPermissionAddPersonnel {
            get {
                return ResourceManager.GetString("NoPermissionAddPersonnel", resourceCulture);
            }
        }
        
        internal static string AlreadyMember {
            get {
                return ResourceManager.GetString("AlreadyMember", resourceCulture);
            }
        }
        
        internal static string AccountCreatedMailSent {
            get {
                return ResourceManager.GetString("AccountCreatedMailSent", resourceCulture);
            }
        }
        
        internal static string MailNotSent {
            get {
                return ResourceManager.GetString("MailNotSent", resourceCulture);
            }
        }
        
        internal static string ExistingUserAdded {
            get {
                return ResourceManager.GetString("ExistingUserAdded", resourceCulture);
            }
        }
        
        internal static string BusinessVerificationTitle {
            get {
                return ResourceManager.GetString("BusinessVerificationTitle", resourceCulture);
            }
        }
        
        internal static string EmailHello {
            get {
                return ResourceManager.GetString("EmailHello", resourceCulture);
            }
        }
        
        internal static string VerificationCodeFor {
            get {
                return ResourceManager.GetString("VerificationCodeFor", resourceCulture);
            }
        }
        
        internal static string PasswordResetTitle {
            get {
                return ResourceManager.GetString("PasswordResetTitle", resourceCulture);
            }
        }
        
        internal static string PasswordResetSubject {
            get {
                return ResourceManager.GetString("PasswordResetSubject", resourceCulture);
            }
        }
        
        internal static string AccountCreatedTitle {
            get {
                return ResourceManager.GetString("AccountCreatedTitle", resourceCulture);
            }
        }
        
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        internal static string AccountCreatedSubject {
            get {
                return ResourceManager.GetString("AccountCreatedSubject", resourceCulture);
            }
        }
        
        internal static string NewBusinessTitle {
            get {
                return ResourceManager.GetString("NewBusinessTitle", resourceCulture);
            }
        }
        
        internal static string BusinessAddedYou {
            get {
                return ResourceManager.GetString("BusinessAddedYou", resourceCulture);
            }
        }
        
        internal static string BusinessAddedSubject {
            get {
                return ResourceManager.GetString("BusinessAddedSubject", resourceCulture);
            }
        }
        
        internal static string BusinessInvitationTitle {
            get {
                return ResourceManager.GetString("BusinessInvitationTitle", resourceCulture);
            }
        }
        
        internal static string BusinessInvitingYou {
            get {
                return ResourceManager.GetString("BusinessInvitingYou", resourceCulture);
            }
        }
        
        internal static string AlreadyPersonnel {
            get {
                return ResourceManager.GetString("AlreadyPersonnel", resourceCulture);
            }
        }
        
        internal static string DirectlyAdded {
            get {
                return ResourceManager.GetString("DirectlyAdded", resourceCulture);
            }
        }
        
        internal static string NewUserAddedComplete {
            get {
                return ResourceManager.GetString("NewUserAddedComplete", resourceCulture);
            }
        }
        
        internal static string ExistingUserAddedComplete {
            get {
                return ResourceManager.GetString("ExistingUserAddedComplete", resourceCulture);
            }
        }
        
        internal static string MailSentErrorSuffix {
            get {
                return ResourceManager.GetString("MailSentErrorSuffix", resourceCulture);
            }
        }
        
        internal static string ProcessSuccessful {
            get {
                return ResourceManager.GetString("ProcessSuccessful", resourceCulture);
            }
        }
        
        internal static string PersonnelRole {
            get {
                return ResourceManager.GetString("PersonnelRole", resourceCulture);
            }
        }
        
        internal static string StartDateAfterEndDate {
            get {
                return ResourceManager.GetString("StartDateAfterEndDate", resourceCulture);
            }
        }
        
        internal static string BusinessMembershipNotFound {
            get {
                return ResourceManager.GetString("BusinessMembershipNotFound", resourceCulture);
            }
        }
        
        internal static string LeaveRequestCreated {
            get {
                return ResourceManager.GetString("LeaveRequestCreated", resourceCulture);
            }
        }
        
        internal static string MembershipNotFound {
            get {
                return ResourceManager.GetString("MembershipNotFound", resourceCulture);
            }
        }
        
        internal static string LeaveRequestNotFound {
            get {
                return ResourceManager.GetString("LeaveRequestNotFound", resourceCulture);
            }
        }
        
        internal static string LeaveStatusUpdated {
            get {
                return ResourceManager.GetString("LeaveStatusUpdated", resourceCulture);
            }
        }
        
        internal static string CannotDeleteProcessedLeave {
            get {
                return ResourceManager.GetString("CannotDeleteProcessedLeave", resourceCulture);
            }
        }
        
        internal static string LeaveRequestDeleted {
            get {
                return ResourceManager.GetString("LeaveRequestDeleted", resourceCulture);
            }
        }
        
        internal static string YouLabel {
            get {
                return ResourceManager.GetString("YouLabel", resourceCulture);
            }
        }
        
        internal static string BusinessOrUserNotFound {
            get {
                return ResourceManager.GetString("BusinessOrUserNotFound", resourceCulture);
            }
        }
        
        internal static string EmployeeNotActiveInBusiness {
            get {
                return ResourceManager.GetString("EmployeeNotActiveInBusiness", resourceCulture);
            }
        }
        
        internal static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        internal static string AiServiceError {
            get {
                return ResourceManager.GetString("AiServiceError", resourceCulture);
            }
        }
        
        internal static string AiResponseReadError {
            get {
                return ResourceManager.GetString("AiResponseReadError", resourceCulture);
            }
        }
        
        internal static string PerformanceReportError {
            get {
                return ResourceManager.GetString("PerformanceReportError", resourceCulture);
            }
        }
        
        internal static string ReportsFetchError {
            get {
                return ResourceManager.GetString("ReportsFetchError", resourceCulture);
            }
        }
        
        internal static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        internal static string SavedReportReadError {
            get {
                return ResourceManager.GetString("SavedReportReadError", resourceCulture);
            }
        }
        
        internal static string BusinessIdRequired {
            get {
                return ResourceManager.GetString("BusinessIdRequired", resourceCulture);
            }
        }
        
        internal static string BulkPerformanceError {
            get {
                return ResourceManager.GetString("BulkPerformanceError", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        internal static string CurrentPasswordWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordWrong", resourceCulture);
            }
        }
        
        internal static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateError {
            get {
                return ResourceManager.GetString("ProfileUpdateError", resourceCulture);
            }
        }
        
        internal static string PersonnelNotActiveInBusiness {
            get {
                return ResourceManager.GetString("PersonnelNotActiveInBusiness", resourceCulture);
            }
        }
        
        internal static string TaskCreateError {
            get {
                return ResourceManager.GetString("TaskCreateError", resourceCulture);
            }
        }
        
        internal static string TasksFetchError {
            get {
                return ResourceManager.GetString("TasksFetchError", resourceCulture);
            }
        }
        
        internal static string MyTasksFetchError {
            get {
                return ResourceManager.GetString("MyTasksFetchError", resourceCulture);
            }
        }
        
        internal static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        internal static string TaskUpdated {
            get {
                return ResourceManager.GetString("TaskUpdated", resourceCulture);
            }
        }
        
        internal static string TaskUpdateError {
            get {
                return ResourceManager.GetString("TaskUpdateError", resourceCulture);
            }
        }
        
        internal static string NoPermissionDeleteTask {
            get {
                return ResourceManager.GetString("NoPermissionDeleteTask", resourceCulture);
            }
        }
        
        internal static string TaskDeleted {
            get {
                return ResourceManager.GetString("TaskDeleted", resourceCulture);
            }
        }
        
        internal static string TaskDeleteError {
            get {
                return ResourceManager.GetString("TaskDeleteError", resourceCulture);
            }
        }
        
        internal static string TaskCreated {
            get {
                return ResourceManager.GetString("TaskCreated", resourceCulture);
            }
        }
        
        internal static string StatusOverdue {
            get {
                return ResourceManager.GetString("StatusOverdue", resourceCulture);
            }
        }
        
        internal static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        internal static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
    }
}
